/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

import "sst"
declare module "sst" {
  export interface Resource {
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "NotifyHubApi": cloudflare.Service
    "NotifyHubDb": cloudflare.D1Database
    "NotifyHubKV": cloudflare.KVNamespace
    "NotifyHubQueue": cloudflare.Queue
  }
}

import "sst"
export {}